name: truk_fleet
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  android_intent: ^2.0.0
  background_location: ^0.7.0
  badges: ^2.0.1
  bitmap: ^0.1.2
  cached_network_image: ^3.0.0
  carousel_pro: ^1.0.0
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.0
  dio: ^4.0.0
  dotted_border: ^2.0.0+1
  equatable: ^2.0.0
  expandable: ^5.0.1
  fast_immutable_collections: ^7.0.3
  file_picker: ^4.1.3
  firebase_auth: ^3.1.2
  firebase_core: ^1.0.3
  firebase_storage: ^10.0.4
  flutter_bloc: ^7.0.0
  flutter_credit_card: ^3.0.0
  flutter_datetime_picker: ^1.4.0
  flutter_google_places: ^0.3.0
  firebase_messaging: ^10.0.4
  mailer: ^5.0.1
  pdf: any
  sendgrid_mailer: ^0.1.3
  flutter_local_notifications: ^9.0.0
  flutter_phoenix: ^1.0.0
  flutter_polyline_points: ^1.0.0
  flutter_share_me: ^1.2.0
  flutter_slidable: ^0.6.0
  month_picker_dialog: ^0.4.0
  flutter_svg: ^0.22.0
  flutter_tawk: ^0.0.5
  fluttertoast: ^8.0.3
  focused_menu: ^1.0.2
  geo_firestore_flutter: ^0.1.1
  geocoder: ^0.2.1
  geolocator: ^7.0.1
  google_maps_flutter: ^2.0.2
  image_picker: ^0.8.4+2
  image_viewer: ^1.0.0
  intl: ^0.17.0
  loading_overlay: ^0.3.0
  location: ^4.1.1
  map_launcher: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  package_info: ^2.0.0
  permission_handler: ^8.2.2
  photo_view: ^0.13.0
  provider: ^6.0.1
  pull_to_refresh: ^2.0.0
  razorpay_flutter:
#  razorpay_flutter: ^1.2.5
  shared_preferences: ^2.0.5
  flutter_image_compress: ^1.0.0-nullsafety
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.3
  uuid: ^3.0.3
  flutter_markdown: ^0.6.7
  change_app_package_name: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/destination_map_marker.png
    - assets/driving_pin.png
    - assets/images/
    - assets/svg/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
